[blockchain]
[blockchain.ethereum]
api = "https://mainnet.infura.io/v3/test"
symbol = "eth"
start_block = 19000000
interval_secs = 5

[repository]
memory_db = true
postgresql_url = "postgres://dummy:dummy@localhost:5432/dummy"
leveldb_path = "./dummy_db"
customer_address_file = "./customer_addresses.txt"
